mysite/attendance/urls.py
from django.urls import path
from . import views

app_name = "attendance"   
urlpatterns = [
    path('', views.index, name = "index"),
    path('train', views.train_model, name = "train" ),
    path('add_student', views.add_student, name = "add_student"),
    path('start_streaming', views.start_streaming, name = "start_streaming"),
    # path('video_streaming', qviews.video_streaming, name = "video_streaming"),
    path('display',views.display, name = "display"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('attendance/',include('attendance.urls')),
    path('admin/', admin.site.urls),
]

mysite/attendance/models.py
from django.db import models

# Create your models here.

#faculty has a name and id
class Faculty(models.Model):
    faculty_id = models.CharField(max_length = 10, default = "")
    name = models.CharField(max_length = 32, default = "")

    def __unicode__(self):
        return self.name

# each subject has a faculty (one to many)
# each subject has id, name and faculty info
class Subject(models.Model):
    subject_id = models.CharField(max_length = 10, default = "")
    subject_name = models.CharField(max_length = 32, default = "")
    faculty = models.ForeignKey(Faculty,on_delete=models.CASCADE)
    
    def __unicode__(self):
        return self.subject_name

# each class on a particular day has 7 periods
# each period has a subject and vice versa
class DailyTimeTable(models.Model):
    period1 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name = "period1")
    period2 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name = "period2")
    period3 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name = "period3")
    period4 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name = "period4")
    period5 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name = "period5")
    period6 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name = "period6")
    period7 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name = "period7")

# each class has a weekly time table
# each day has a daily time table which is one to one
class WeeklyTimeTable(models.Model):
    tuesday = models.ForeignKey(DailyTimeTable,   on_delete=models.CASCADE, related_name = "tuesday")
    wednesday = models.ForeignKey(DailyTimeTable, on_delete=models.CASCADE, related_name = "wednesday")
    thursday = models.ForeignKey(DailyTimeTable,  on_delete=models.CASCADE, related_name = "thursday")
    friday = models.ForeignKey(DailyTimeTable,    on_delete=models.CASCADE, related_name = "friday")
    saturday = models.ForeignKey(DailyTimeTable,  on_delete=models.CASCADE, related_name = "saturday")

# there are many classes 
# each class has branch, year, # of students and time table
# every class is assigned with a weekly time table
class Class(models.Model):
    branch = models.CharField(max_length = 5, default = "")
    section = models.CharField(max_length = 2, default = "")
    year = models.IntegerField(default = 1)
    no_of_students = models.IntegerField(default = 60)
    time_table = models.ForeignKey(WeeklyTimeTable, on_delete=models.CASCADE)
    def __unicode__(self):
        return self.branch+" "+self.year+self.section

# for every subject attendance has to be taken 
class SubjectAttendanceTable(models.Model):
    subject = models.OneToOneField(Subject, on_delete=models.CASCADE)
    attendance_count = models.IntegerField(default = 0)

# each student has 6 subjects
# each subject has attendance to be maintained
class StudentAttendanceTable(models.Model):
    subject1 = models.OneToOneField(SubjectAttendanceTable, on_delete=models.CASCADE, related_name = "subject1")
    subject2 = models.OneToOneField(SubjectAttendanceTable, on_delete=models.CASCADE, related_name = "subject2")
    subject3 = models.OneToOneField(SubjectAttendanceTable, on_delete=models.CASCADE, related_name = "subject3")
    subject4 = models.OneToOneField(SubjectAttendanceTable, on_delete=models.CASCADE, related_name = "subject4")
    subject5 = models.OneToOneField(SubjectAttendanceTable, on_delete=models.CASCADE, related_name = "subject5")
    subject6 = models.OneToOneField(SubjectAttendanceTable, on_delete=models.CASCADE, related_name = "subject6")
    subject7 = models.OneToOneField(SubjectAttendanceTable, on_delete=models.CASCADE, related_name = "subject7")


# every student has a class (many to one)
# every student has roll_no, name, section and attendance
# attendance is the collection of all his subjects
class Student(models.Model):
    roll_no = models.CharField(max_length = 10, default = "")
    name = models.CharField(max_length = 32, default = "")
    section = models.ForeignKey(Class, on_delete=models.CASCADE)
    # attendance = models.OneToOneField(StudentAttendanceTable, on_delete=models.CASCADE)
    
    def __unicode__(self):
        return self.roll_no


class Attendance(models.Model):
    roll_no = models.CharField(max_length = 10, default = "")
    # we will get name, class and section from the rollno
    branch = models.CharField(max_length = 10, default = "")
    section = models.CharField(max_length = 10, default = "")
    period = models.CharField(max_length = 10, default = "")
    date = models.CharField(max_length = 10, default = "")
    time = models.CharField(max_length = 10, default = "")
    status = models.CharField(max_length = 10, default = "Absent")

    def __unicode__(self):
        return self.roll_no + self.section + self.period 
    
class UploadFile(models.Model):
    files = models.FileField(upload_to='myfiles/', blank=True, null=True)

mysite/attendance/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import UploadFile  
class FileUpload(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ['files']
        widgets = {
            'files': ClearableFileInput(attrs={'multiple'
            : True}),
        }

mysite/attendance/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, StreamingHttpResponse
from .models import *
import os,threading
import cv2
from .main.face_embeddings import *
from .main.face_recognition_video import *
from .main.save_faces import *
from .main.face_classification import *
from .main.requirements import *
from .forms import FileUpload
from django.core.files.storage import FileSystemStorage
from pathlib import Path
from django.views.decorators.csrf import csrf_exempt
from .main.response_codes import get_response_status
import json
from .main.utils import *
from django.views.decorators.gzip import gzip_page

BASE_DIR = Path(__file__).resolve().parent.parent

def index(request):
    students_info = Student.objects.all()

    if request.method == "POST":
        files = request.FILES.getlist("files")
        print("hello", files)
        for file in files:
            print(file)
    return render(request, 'attendance/index.html', { 'students_info' : students_info })

def train_model(request):
    # call the html file
    save_faces()
    face_embeddings()
    face_classification()
    return render(request, 'attendance/train.html')


def add_student(request):
    if request.method == "POST":
        form = FileUpload(request.POST, request.FILES)
        print(request.POST)
        files = request.FILES.getlist('files')
        if form.is_valid() and len(files)==20:
            if post_student_info(request.POST):
                for i in range(0,len(files)):
                    f = files[i]
                    # file_instance = UploadFile(files=f)
                    # file_instance.save()
                    # for storing files in the specific directory with rollno as a directory name
                    location = os.path.join(BASE_DIR,'attendance/images/train/'+request.POST['roll_no']+'/')
                    if i in range(15,20):
                        location = os.path.join(BASE_DIR,'attendance/images/val/'+request.POST['roll_no']+'/')
                    print(str(location)) 
                    fs = FileSystemStorage(location = location ) 
                    file = fs.save(f.name, f) 
                    fileurl = fs.url(file) 
                print("Uploaded files successfully!")
            else:
                print("Student not added!")
        else:
            print("Files not uploaded!")
        return redirect('/attendance')  

    else:
         form = FileUpload()
    return render(request, 'attendance/add_student.html')

def start_streaming(request):
    face_recognition_video()
    return render(request, 'attendance/start_streaming.html')



@csrf_exempt
def display(request):
    if request.method == "POST":
        print(request.POST)  

        if "section_info" in request.POST.keys():
            # print(request.POST)
            print("came to section info")
            branch = request.POST["section_info"]
            status_code = 200
            sections_info = get_all_sections(branch)  
            return HttpResponse(json.dumps({'Message': 'Success!', 'data': sections_info}, cls=Encoder),
                            content_type="application/json", status=get_response_status(status_code))

        elif "section_no" in request.POST.keys() and "class_name" in request.POST.keys():
            print("came to section no and class no")
            try:
                section_attendance,status_code = get_section_attendance(request.POST['class_name'],request.POST['section_no'],request.POST['period_no'],request.POST['date'])
                if status_code==200:
                    return HttpResponse(json.dumps({'Message': 'Success!', 'data': section_attendance}, cls=Encoder),
                                content_type="application/json", status=get_response_status(status_code))
                else:
                    return HttpResponse(json.dumps({'Message': 'failure'}, cls=Encoder),
                                content_type="application/json", status=get_response_status(status_code))
            except Exception as e:
                print(e)
                return HttpResponse(json.dumps({'Message': 'failure'}, cls=Encoder),
                                content_type="application/json", status=get_response_status(500))
        else:
            print("came to else part")
            all_branches = get_all_branches()
            status_code = 200
            return HttpResponse(json.dumps({'Message': 'Success!', 'data': all_branches}, cls=Encoder),
                            content_type="application/json", status=get_response_status(status_code))
            
    return render(request, 'attendance/display.html')






# # def video_streaming(request):
# #     return StreamingHttpResponse(face_recognition_video())
# class VideoCamera(object):
#     def __init__(self):
#         self.video = cv2.VideoCapture(0)
#         (self.grabbed, self.frame) = self.video.read()
#         threading.Thread(target=self.update, args=()).start()

#     def __del__(self):
#         self.video.release()

#     def get_frame(self):
#         image = self.frame
#         ret, jpeg = cv2.imencode('.jpg', image)
#         return jpeg.tobytes()

#     def update(self):
#         while True:
#             (self.grabbed, self.frame) = self.video.read()


# vc= VideoCamera()


# def gen(camera):
#     while vc.isOpened() :
#         ret,frame = vc.read()
#         if not ret:
#             break
#         cv2.imshow('camera',frame)
#         yield(b'--frame\r\n'
#               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
#         if cv2.waitKey(1) & 0xFF==ord('q'):
#             temp = False


# @gzip_page
# def video_streaming(request):
#     try:
#         return StreamingHttpResponse(gen(VideoCamera()), content_type="multipart/x-mixed-replace;boundary=frame")
#     except:  # This is bad! replace it with proper handling
#         pass

mysite/attendance/templates/attendance/add_student.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    
    <title>Attendance Management</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->

  </head>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script>

    function validate()
    {
      files = document.getElementById("files"); 
      if( files.files.length!=20)
      { 
        console.log(files)
        console.log("Please select 20 files");
        window.alert("Please select exactly 20 files");
        window.location.href = "/attendance/add_student";
      } 
      else 
      {
        console.log("proceeding forward...")
      }
    }

</script>
  <body>

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
        <h1 class = "display-3">Welcome to</h1>
      <h1 class="display-4">Registration Page</h1>
        </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Registration</h2>
         <form method = "post" action = "/attendance/add_student" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="">Name</label>
            <input type="text" name = "name" class="form-control" id="" placeholder="Enter Name" required>
          </div>
          <div class="form-group">
            <label for="">Roll Number</label>
            <input type="text" name = "roll_no" class="form-control" id="" placeholder="Enter Roll Number" required>
          </div>
          <div class="form-group">
            <label for="">Section</label>
            <input type="text" name = "section" class="form-control" id="" placeholder="Enter Section" required>
          </div>
          <div class="form-group">
            <label for="">Branch</label>
            <input type="text" name = "branch" class="form-control" id="" placeholder="Enter Branch" required>
          </div>
          <div class="form-group">
            <label>Please provide 20 images of yours</label>
            <input  type="file" name = "files" class="form-control-file" onchange = "validate()" id="files" multiple required>
          </div>
          <button type="submit" class="btn btn-primary">Register</button>
        </form>
      </div>
      
    </div>

    <hr>

  </div> 

</main>

<footer class="container">
  <p>&copy; M K V Kishore</p>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</html> 

mysite/attendance/templates/attendance/display.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    
    <title>Attendance Management</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- for google charts -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> 

    {% load static %}

    <script src = " {% static '/attendance/js/display.js' %} "></script>

  </head>
  
  <body>

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
        <h1 class = "display-6">Dynamic Attendance Display</h1>
      <!-- <h1 class="display-4">Attendance Management System</h1> -->
      <!-- Date:<div id="datepicker"></div>-->
       
        </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="jumbotron col-md-4" style="background-color:#d8363624">
        <h4>Select Date</h4>
        <input type = "date" id = "selected_date">  
      </div>
      <div style= "background-color:rgb(0 75 243 / 31%); width: fit-content; height: fit-content;" id = "side_bar" class="jumbotron col-md-8">
          <div style="display: none;" id = "all-info" >
            <h4>Display All Information</h4>
            <div class = "row">
              <div class = "col-md-4" id = "classes-info">
                <h5>Select Class</h5>
                <select class = "form-control btn-dark">
                  <option  class = 'form-control' disabled selected value>--</option>
                </select>
              </div>
              <div class = "col-md-4" id = "section-info">
                <h5>Select Section</h5>
                <select class = "form-control btn-dark">
                  <option  class = 'form-control' disabled selected value>--</option>
                </select>
              </div>
              <div class = "col-md-4" id = "period-info">
                <h5>Select Period</h5>
                <select class = "form-control btn-dark">
                  <option  class = 'form-control' disabled selected value>--</option>
                </select>
              </div>

            </div>

          </div>
        </div>
      </div>
     
      <div class = "jumbotron" style="background-color: #82ec90a1;margin: 0%;">
        <div id="table_div" ></div>
  
  
      </div>
    </div>
   
    <hr>

  </div> <!-- /container -->

</main>
<div class = "container">
  
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<footer class="container">
  <p>&copy; M K V Kishore</p>
</footer>
</html> 

mysite/attendance/templates/attendance/index.html
<!-- <body>
    <ul>
        {% for student in students_info %}
            <li>{{ student.name }}
                <ul>
                    <li>{{ student.id }}</li>
                    <li>{{ student.roll_no }}</li>
                </ul>
            </li>

        {% endfor %}
    </ul>
</body> -->

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    
    <title>Attendance Management</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->

  </head>
  <body>

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
        <h1 class = "display-3">Welcome to</h1>
      <h1 class="display-4">Attendance Management System</h1>
        </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-3">
        <h2>Register Now!</h2>
        <p>This is the <b>Phase 1</b></p>
        <p>We are very delighted to have you here.</p>
        <p>If you want to register your name as a student then please click here.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'attendance:add_student' %}" role="button">Register &raquo;</a></p>
      </div>
      <div class="col-md-3">
        <h2>Train Now!</h2>
        <p>This is the <b>Phase 2</b></p>
        <p>Here, we are going to train entire data.</p>
        <p>This process will take time. It's time to test your patience :)</p>
        <p><a class="btn btn-primary btn-lg" onclick="alert('This will train entire data')"  href="{% url 'attendance:train' %}" role="button">Train &raquo;</a></p>
       
      </div>
      <div class="col-md-3">
        <h2>Stream Now!</h2>
        <p>This is the <b>Phase 3</b></p>
        <p>We are going to start the cameras of the classrooms to retrive data.</p>
        <p>We can see the rectangular box on every face in our live feed.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'attendance:start_streaming' %}" role="button">Stream &raquo;</a></p>
       
      </div>
      <div class="col-md-3">
        <h2>Display Now!</h2>
        <p>This is the <b>Phase 4</b></p>
        <p>Each and every information is stored in our database.</p>
        <p>To have a look into it, please click below.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'attendance:display' %}" role="button">Display &raquo;</a></p>
       
      </div>
      
    </div>

    <hr>

  </div> <!-- /container -->

</main>

<footer class="container">
  <p>&copy; M K V Kishore</p>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</html> 

mysite/attendance/templates/attendance/start_streaming.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    
    <title>Attendance Management</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">



    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->

  </head>
  <body>

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
        <h1 class = "display-3">Welcome to</h1>
      <h1 class="display-4">Streaming Page</h1>
        </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-6">
        <h2>Hope you enjoyed our streaming!</h2>
        <p>Now you can go to display page or do another registration :) </p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'attendance:add_student' %}" role="button">Register &raquo;</a>
        <a class="btn btn-primary btn-lg" href="{% url 'attendance:display' %}" role="button">Display &raquo;</a></p>
      </div>
      
    </div>

    <hr>

  </div> <!-- /container -->

</main>

<footer class="container">
  <p>&copy; M K V Kishore</p>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</html> 

mysite/attendance/templates/attendance/train.html
<!-- <body>
    <ul>
        {% for student in students_info %}
            <li>{{ student.name }}
                <ul>
                    <li>{{ student.id }}</li>
                    <li>{{ student.roll_no }}</li>
                </ul>
            </li>

        {% endfor %}
    </ul>
</body> -->

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    
    <title>Attendance Management</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->

  </head>
  <body>

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
        <h1 class = "display-3">Welcome to</h1>
      <h1 class="display-4">Training Page</h1>
        </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-6">
        <h2>Training is done!</h2>
        <h3>Thanks for waiting this far!!</h3>
        <p>You can now stream and manage the attendance</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'attendance:start_streaming' %}" role="button">Register &raquo;</a>
          <a class="btn btn-primary btn-lg" href="{% url 'attendance:start_streaming' %}" role="button">Stream &raquo;</a>
        </p>
        
        
      </div>
      
    </div>

    <hr>

  </div> <!-- /container -->

</main>

<footer class="container">
  <p>&copy; M K V Kishore</p>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script></body>
</html> 